# Generated by Django 2.2.6 on 2019-10-12 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jikkyotter', '0002_auto_20191012_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 23, 45, 18, 390647), verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 23, 45, 18, 392216), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 23, 45, 18, 392196), verbose_name='開始日時'),
        ),
    ]
