# Generated by Django 2.2.6 on 2019-10-12 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jikkyotter', '0006_auto_20191013_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 23, 35, 47, 282088, tzinfo=utc), verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 23, 35, 47, 283673, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 23, 35, 47, 283652, tzinfo=utc), verbose_name='開始日時'),
        ),
    ]
