# Generated by Django 2.2.6 on 2019-10-12 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jikkyotter', '0007_auto_20191013_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時'),
        ),
    ]
