# Generated by Django 2.2.6 on 2019-10-30 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jikkyotter', '0011_auto_20191030_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時'),
        ),
    ]
