# Generated by Django 2.2.6 on 2019-10-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jikkyotter', '0012_auto_20191030_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_at',
            field=models.DateTimeField(verbose_name='開始日時'),
        ),
    ]
