# Generated by Django 2.2.6 on 2019-10-30 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jikkyotter', '0013_auto_20191030_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時'),
        ),
    ]
